# Generated by Django 2.1.1 on 2018-10-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
