# Generated by Django 2.1.1 on 2018-10-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_remove_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
